### ISSUE TITLE
Bower build failed -  ECONFLICT Unable to find suitable version for xxx

### ISSUE THREAD

**Issue by ddesani** [craigburke/bower-installer-gradle#10]
Hi Craig,
First of all, thanks sharing and supporting this project! I've been manually managing the .js files for angular but now I'm playing with bower and your plugin, so pardon me if the solution is something simple that I haven't noticed.

Here's my setup:
- OSX 10.10
- Grails 3.1.4 project

I'm able to add the following libraries to the project with no problem:
```
'angular'('1.5.x') {
        source 'angular.js' >> '/js/angular/'
        source 'angular.min.js' >> '/js/angular/'
        source '*.css' >> '/css/angular/'
    }
    'angular-aria'('1.5.x') {
        source 'angular-aria.js' >> '/js/angular/'
        source 'angular-aria.min.js' >> '/js/angular/'
        source '*.css' >> '/css/angular/'
    }
    'angular-animate'('1.5.x') {
        source 'angular-animate.js' >> '/js/angular/'
        source 'angular-animate.min.js' >> '/js/angular/'
        source '*.css' >> '/css/angular/'
    }
    'angular-resource'('1.5.x') {
        source 'angular-resource.js' >> '/js/angular/'
        source 'angular-resource.min.js' >> '/js/angular/'
        source '*.css' >> '/css/angular/'
    }
    'angular-mocks'('1.5.x') {
        source '*.js' >> '/js/angular/'
        source '*.css' >> '/css/angular/'
    }
    'angular-route'('1.5.x'){
        source 'angular-route.js' >> '/js/angular/'
        source 'angular-route.min.js' >> '/js/angular/'
        source '*.css' >> '/css/angular/'
    }
    'angular-material-icons'('0.7.0'){
        source 'angular-material-icons.js' >> '/js/angular/'
        source 'angular-material-icons.min.js' >> '/js/angular/'
        source '*.css' >> '/css/angular/'
    }
    'angular-messages'('1.5.x'){
        source 'angular-messages.js' >> '/js/angular/'
        source 'angular-messages.min.js' >> '/js/angular/'
        source '*.css' >> '/css/angular/'
    }

    'angular-material'('1.0.7'){
        source 'angular-material.js' >> '/js/angular/'
        source 'angular-material.min.js' >> '/js/angular/'
        source '*.css' >> '/css/angular/'
    }
```

However, when I try running bowerRefresh after adding [angular-chart.js](https://github.com/jtblin/angular-chart.js) the output gives me the following error:
```
grails> gradle bowerRefresh
:bowerInit UP-TO-DATE
:nodeSetup UP-TO-DATE
:bowerDependencies UP-TO-DATE
:bowerConfig
:bowerClean
:bowerComponents
bower Chart.js#~1.0.1                        invalid-meta Chart.js is missing "ignore" entry in bower.json
bower                                           ECONFLICT Unable to find suitable version for Chart.js
:bowerComponents FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':bowerComponents'.
> Process 'command '/Users/xxx/.gradle/nodejs/node-v4.2.3-darwin-x64/bin/node'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 9.425 secs
| Error Command [gradle] error: Could not execute build using Gradle distribution 'https://services.gradle.org/distributions/gradle-2.3-all.zip'. (Use --stacktrace to see the full trace)
```

The message below shows that there's a problem with Chart.js. I've tried your `excludes 'Chart.js'`, but it hasn't changed the output. 
```
bower Chart.js#~1.0.1                        invalid-meta Chart.js is missing "ignore" entry in bower.json
bower                                           ECONFLICT Unable to find suitable version for Chart.js
```

How could I proceed in order to have that library managed by bower? Btw, I've noticed that the embedded bower is from version 1.3.12. How could I have/use the latest bower with your plugin? Is there a way to append a "-F" (--force-latest) for dependencies?

Thank you!

**Comment by craigburke** [comment]
This plugin is a wrapper for bower-installer which unfortunately hasn't been updated for a while and is looking for a new owner/maintainer:
https://github.com/blittle/bower-installer/issues/149

If you can throw an issue with your full bower config, I'd love to walk you throw migrating to this plugin:
https://github.com/craigburke/client-dependencies-gradle

**Comment by ddesani** [comment]
Thanks Craig! 
I've moved my dependencies to your plugin and it works fine now. 

Just a little and last question, maybe I should open an issue there, but is there a way to mange the destination of each file with 'client-dependencies-gradle' plugin? 

For example, *.css and *.js files from a dependency into different directories (here we can use '>>' right after the file name). From your examples I assume that only one 'into' can be used.

Thanks again.

**Comment by craigburke** [comment]
@desani I actually prefer to have the dependencies in separate folders (otherwise you run the risk of files getting overwritten). You do actually have full control over where the individual files land. 

Here's an example of the kind of thing you could do:
```
'angular'('1.5.x') {
    eachFile {
        String fileExtension = it.path.tokenize('.').last()
        it.path = "../${fileExtension}/${it.relativePath}"
    }
}
```
Which you could make the default copy definition for all your dependencies like so:
```
clientDependencies {
    defaultCopy = {
        eachFile {
            String fileExtension = it.path.tokenize('.').last()
            it.path = "../${fileExtension}/${it.relativePath}"
        }
    }
}
```
In both cases you can use all the same methods or properties you'd use in a Gradle copy task: https://docs.gradle.org/current/dsl/org.gradle.api.tasks.Copy.html

Hopefully that helps (but I still recommend keeping everything in separate folders 😄).

**Comment by ddesani** [comment]
That was a great response! I will take into account your point about deps per folder =).

Thanks Craig, I believe we covered everything 😄.
