### ISSUE TITLE
Limited internet connection

### ISSUE THREAD

**Issue by Luxor** [craigburke/bower-installer-gradle#11]
Hi,

I am trying to use the plugin as part of grails 3. I have only limited internet connection.
Once I trying to run the application with bower plugin, I got:

```
* What went wrong:
Could not resolve all dependencies for configuration ':nodeDist'.
> Could not resolve org.nodejs:node:4.2.3.
  Required by:
      ang2:ang2:0.1
   > Could not resolve org.nodejs:node:4.2.3.
      > Could not get resource 'https://nodejs.org/dist/v4.2.3/ivy.xml'.
         > Could not GET 'https://nodejs.org/dist/v4.2.3/ivy.xml'.
            > Connection to https://nodejs.org refused
> Could not resolve org.nodejs:win-x64/node:4.2.3.
  Required by:
      ang2:ang2:0.1
   > Could not resolve org.nodejs:win-x64/node:4.2.3.
      > Could not get resource 'https://nodejs.org/dist/v4.2.3/ivy.xml'.
         > Could not GET 'https://nodejs.org/dist/v4.2.3/ivy.xml'.
            > Connection to https://nodejs.org refused

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
```

Can I point nodejs to local installation? please advice
Also can I use local corporate npm repository.

Thanks

**Comment by craigburke** [comment]
@Luxor so you have two options here. 

This plugin leverages the gradle-node-plugin so you can configure that plugin to use a local node install. Check out the docs here:
https://github.com/srs/gradle-node-plugin

Another option is to checkout my newer gradle plugin which uses the bower/npm repositories but doesn't use node at all so it should work better for you in general with limited connectivity:
https://github.com/craigburke/client-dependencies-gradle

**Comment by Luxor** [comment]
Thank you. Will take a look at client dependencies!

**Comment by craigburke** [comment]
@Luxor no problem. If you want help migrating from this plugin to client dependencies just throw an issue up on that project and I can walk you through it.
