### ISSUE TITLE
Support resolutions

### ISSUE THREAD

**Issue by sreque** [craigburke/bower-installer-gradle#13]
http://jaketrent.com/post/bower-resolutions/

When two packages have conflicting dependencies, there appears to be no way to configure the plugin to resolve dependencies.

**Comment by craigburke** [comment]
@sreque you can accomplish the same thing by just declaring the dependency at a specific version. 

You might want to check out this project which gives you more control and supports both npm and bower:
https://github.com/craigburke/client-dependencies-gradle

If you want help moving your current config to use that plugin, just throw an issue up and I can guide you through it.
