### ISSUE TITLE
Can't properly resolve dependencies requiring a "resolution" block

### ISSUE THREAD

**Issue by skuphmarx** [craigburke/bower-installer-gradle#14]
If the dependencies require a resolution to a conflicted common dependency (multiple versions) the regular bower install command interactively asks a question and adds a resolution block to the bower.json. There is no way to do that here. I have tried to do so in the "additional" section, however the resolution breaks prior to reaching this and the "additional" params never make it into the bower.json file

**Comment by leolion75** [comment]
I was able to resolve this issue by cloning the project and updating the following files: BowerModuleExtension and BowerJson.

BowerModuleExtension: add 
```groovy 
Map resolutions = [:]
```
BowerJson: in the generateBasic method add a new key to the bowerJson map:
```groovy
if (bowerConfig.resolutions) {
    bowerJson.resolutions = bowerConfig.resolutions
}
```
I also updated the build.gradle file to bump version.
```
version = '2.6.0'

ext {
    artifactId = 'bower-installer-gradle'
}
```

After you make the changes, you can deploy to your local maven repo using `gradle publishToMavenLocal`

Last, you would update the build.gradle of your current project as follows:
```groovy

classpath "com.craigburke.gradle:bower-installer-gradle:2.6.0"

bower {
   'angular'('1.5.x') {
        source 'angular.js'
    }
    'fullcalendar'('2.7.1')
    'angular-ui-calendar'('1.0.2')
.
.
resolutions = [
            'angular': '1.5.8'
    ]
}
```

**Comment by craigburke** [comment]
Closing this since this plugin is replaced by the client dependencies gradle plugin:
https://github.com/craigburke/client-dependencies-gradle
