### ISSUE TITLE
Travis error when using bower gradle: cannot read property 'uid' of undefined

### ISSUE THREAD

**Issue by kunkun-tang** [craigburke/bower-installer-gradle#16]
Hi,

Thanks to this plugin, Our project can get artifactory js files easily. However, I got this error in recent travis build, Could you please have a look?

https://travis-ci.org/azkaban/azkaban/builds/162919379

installer/node_modules/bower/node_modules/fstream/node_modules/graceful-fs/polyfills.js:264
      if (stats.uid < 0) stats.uid += 0x100000000
               ^
TypeError: Cannot read property 'uid' of undefined
    at /home/travis/build/azkaban/azkaban/azkaban-web-server/node_modules/bower-installer/node_modules/bower/node_modules/fstream/node_modules/graceful-fs/polyfills.js:264:16

Do you have any thoughts what going on?

Thanks

**Comment by craigburke** [comment]
Closing this since this plugin is replaced by the client dependencies gradle plugin:
https://github.com/craigburke/client-dependencies-gradle
