### ISSUE TITLE
Possible error in generated bower.json

### ISSUE THREAD

**Issue by vitalii-dmytruk** [craigburke/bower-installer-gradle#4]
Bower doesn't install loaded components to desired location on Windows 10.

I'm using the plugin on the Windows machine andhave the output like this:
``` javascript
{
  ...
  "dependencies": {
    "jquery": "2.1.x",
    ...
  },
  "install": {
    ...
    "sources": {
      "jquery": {
        "mapping": [
          {
            "C:/projects/spartan.com/eshu/bower_components/jquery/dist/jquery.js": "jquery.js"
          },
       ...
```

according to the name of variables in the next part of plugin source code 
``` groovy
moduleFiles.each { File file ->
                    String relativePath = normalizePath(file.absolutePath) - "${projectRoot.absolutePath}/"
                    String destination = getDestinationPath(dependency.name, relativePath, key, value)

                    sources[dependency.name].mapping << [ (relativePath) : destination ]
                }
```
and the error I have in result 

```
Error: ENOENT, no such file or directory 'C:\projects\spartan.com\eshu\C:\projects\spartan.com\eshu\bower_components\jquery\dist\jquery.min.js'
```
it looks like key of the mapping object in bower.json must be a relative path of the component.

Unfortunately I don't know groove and it is my first day of Gradle usage, so it really don't know how to write/debug Gradle pugins. So I'm not providing a solution or at least specific place in the code where the possible issue is located. But if all written above make sense, could you please fix this problem.

Thanks in advance.

**Comment by craigburke** [comment]
Huh, that's strange. What does the bower config within your `build.gradle` look like?

**Comment by vitalii-dmytruk** [comment]
@craigburke there is nothing special I think.

``` gradle

bower {
    installBase = 'resources/assets/lib'

    dependencies {

        'jquery'('2.1.x') {
            source 'dist/*'
        }

        'underscore'('1.8.x') {
            source 'underscore*'
        }

        'backbone'('1.2.x') {
            source 'backbone*'
        }

        'requirejs'() {
            source 'require.js'
        }

        'bootstrap'('3.3.x') {
            source 'dist/js/*.min.js' >> 'js'
            source 'dist/css/*.min.css' >> 'styles'
            source 'dist/fonts/**' >> 'fonts'

            excludes 'jquery'
        }
    }

    additional = [
            name: 'custom-name'
    ]
}
```

**Comment by craigburke** [comment]
Nope that all looks pretty normal to me. I'll have to fire up a Windows 10 VM and check it out.

**Comment by vitalii-dmytruk** [comment]
Just in case it matters I'm using Gradle 2.7 and latest bower-installer-gradle v2.1.3

**Comment by teddyyueh** [comment]
I am experiencing the same thing on Windows 8 using Gradle that comes with Grails 3.0 and the latest bower-installer-gradle v2.1.3

**Comment by craigburke** [comment]
@vitalii-dmytruk and @teddyyueh: got sidetrack by work stuff. I'll take a look at this.

**Comment by teddyyueh** [comment]
Thanks, Craig! Let me know if you need any other info.

**Comment by craigburke** [comment]
Ok, @vitalii-dmytruk and @teddyyueh: I think I resolved your issue. 

Give the newly released v2.1.4 a spin and see if helps.

**Comment by teddyyueh** [comment]
'BUILD SUCCESSFUL' and all sources are copied to their specified locations. Thanks!

**Comment by craigburke** [comment]
Woohoo! :+1: :tada:
