### ISSUE TITLE
Dependency by URL

### ISSUE THREAD

**Issue by IsraProductions** [craigburke/bower-installer-gradle#5]
Trying to add a GitHub dependency (that is not registered in Bower) by URL:

bower {
    dependencies {
        'https://github.com/PolymerElements/paper-input.git'('1.0.14')
    }
}

Yeilds the following error:

bower https#*                  ECMDERR Failed to execute "git ls-remote --tags --heads //github.com/PolymerElements/paper-input.git", exit code of #128

Additional error details:
fatal: '//github.com/PolymerElements/paper-input.git' does not appear to be a git repository

**Comment by craigburke** [comment]
Try this:
```
bower {
    dependencies {
        'paper-input'('https://github.com/PolymerElements/paper-input.git#1.0.14')
    }
}
```

**Comment by IsraProductions** [comment]
Yes! It works even without the version fragment. Super!
